
from typing import Protocol, Dict, Any, Sequence

class IStorage(Protocol):
    async def write_lob_updates(self, batch: Sequence[Dict[str, Any]]) -> None: ...
    async def write_trades(self, batch: Sequence[Dict[str, Any]]) -> None: ...
    async def flush(self) -> None: ...
