
from typing import Protocol, Dict, Any, Sequence


class IStorage(Protocol):
    async def write_trades(self, batch: Sequence[Dict[str, Any]]) -> None: ...
    async def write_funding_rates(
        self, batch: Sequence[Dict[str, Any]]
    ) -> None: ...
    async def write_mark_prices(
        self, batch: Sequence[Dict[str, Any]]
    ) -> None: ...
    async def write_tickers(self, batch: Sequence[Dict[str, Any]]) -> None: ...
    async def write_open_interest(
        self, batch: Sequence[Dict[str, Any]]
    ) -> None: ...
    async def write_orderbook_snapshots(
        self, batch: Sequence[Dict[str, Any]]
    ) -> None: ...
    async def write_orderbook_updates(
        self, batch: Sequence[Dict[str, Any]]
    ) -> None: ...
    async def flush(self) -> None: ...
