
from typing import Protocol

class IDQ(Protocol):
    def check_checksum(self, checksum: int, book_levels: int = 25) -> bool: ...
    def check_sequence(self, prev_seq: int, curr_seq: int) -> bool: ...
    def staleness_ms(self, event_ts_ms: int, now_ms: int) -> int: ...
