global:
  scrape_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'okx-collector'
    static_configs:
      - targets: ['collector:9108']
    scrape_interval: 5s
